services:

  postgres-dop:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: dop
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: dop_setting
    ports:
      - "5433:5432"
    volumes:
      - postgres-dop-db:/var/lib/postgresql/data

  redis-dop:
    image: redis
    restart: on-failure
    ports:
      - "6379:6379"
    volumes:
      - redis-dop-db:/data
    command: ["redis-server"]

volumes:
  postgres-dop-db:
  redis-dop-db: