services:

  postgres-dop:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: dop
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: dop
    ports:
      - "5433:5432"
    volumes:
      - postgres-dop-db:/var/lib/postgresql/data

volumes:
  postgres-dop-db: